# fly.toml file generated for emporiumback on 2023-05-22T17:37:56+02:00

app = "emporiumback"
primary_region = "lhr"

[build]
  image = "tarskan/emporiumback:latest"

[http_service]
  internal_port = 9000
  force_https = true

[checks]
  [checks.alive]
    type = "tcp"
    interval = "15s"
    timeout = "2s"
    grace_period = "5s"
