# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1
jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Build Quarkus application
          command: |
            ./mvnw clean install -DskipTests=true

  docker-build-and-push:
    working_directory: /dockerapp
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - run:
          name: Build application Docker image
          command: docker build -t app .
      - deploy:
          name: Publish application to docker hub
          command: |
            docker login -e $DOCKER_HUB_EMAIL -u $DOCKER_HUB_USER_ID -p $DOCKER_HUB_PWD
            docker tag app $DOCKER_HUB_USER_ID/emporiumback:$CIRCLE_BUILD_NUM
            docker tag app $DOCKER_HUB_USER_ID/emporiumback:latest
            docker push $DOCKER_HUB_USER_ID/emporiumback:$CIRCLE_BUILD_NUM
            docker push $DOCKER_HUB_USER_ID/emporiumback:latest
  deploy:
    machine:
      enabled: true
    steps:
      - run:
          name: Install Flyctl CLI
          command: |
            curl -L https://fly.io/install.sh | sh
      - run:
          name: Configure Flyctl
          command: |
            flyctl auth login --email $FLY_EMAIL_USER --password $FLY_PWD_USER
      - run:
          name: Deploy Quarkus application to Fly.io
          command: |
            flyctl deploy --app=$FLY_APP_NAME --image=$FLY_DOCKER_IMAGE


workflows:
  version: 1
  say-hello-workflow:
    jobs:
      - build
      - docker-build-and-push:
          requires:
            - build
      - deploy:
          requires:
            - build
            - docker-build-and-push
