# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

orbs:
  maven: circleci/maven@1.4.1

jobs:
  build: &shared-config
    docker:
      - image: circleci/openjdk:11-jdk
        environment:
          DATABASE_URL: postgresql://localhost:5432/circle_test
          DATABASE_USER: postgres
          DATABASE_PWD: postgrespw
      - image: circleci/postgres:9.6.5
        environment:
          POSTGRES_DB: circle_test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgrespw
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            - v1-dependencies-
      - run:
          name: Build Quarkus application
          command: |
            mvn package
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

  docker-build-and-push:
    <<: *shared-config
    working_directory: /dockerapp
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - run:
          name: Build application Docker image
          command: docker build -f src/main/docker/Dockerfile.deploy -t app .
      - deploy:
          name: Publish application to docker hub
          command: |
            docker login -e $DOCKER_HUB_EMAIL -u $DOCKER_HUB_USER_ID -p $DOCKER_HUB_PWD
            docker tag app $DOCKER_HUB_USER_ID/emporiumback:$CIRCLE_BUILD_NUM
            docker tag app $DOCKER_HUB_USER_ID/emporiumback:latest
            docker push $DOCKER_HUB_USER_ID/emporiumback:$CIRCLE_BUILD_NUM
            docker push $DOCKER_HUB_USER_ID/emporiumback:latest
  deploy:
    machine:
      enabled: true
    steps:
      - run:
          name: Install Flyctl CLI
          command: |
            curl -L https://fly.io/install.sh | sh
            chmod +x /root/.fly/flyctl
      - run:
          name: Configure Flyctl
          command: |
            /root/.fly/flyctl auth login --email $FLY_EMAIL_USER --password $FLY_PWD_USER
      - run:
          name: Deploy Quarkus application to Fly.io
          command: |
            /root/.fly/flyctl deploy --app=$FLY_APP_NAME --image=$FLY_DOCKER_IMAGE


workflows:
  version: 1
  deploy-quarkus-on-fly-io:
    jobs:
      - build
      - docker-build-and-push:
          requires:
            - build
      - deploy:
          requires:
            - build
            - docker-build-and-push